#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`
MAKE = make

all: engines_gweled_gweledengine visualbotngine

engines_gweled_gweledengine: 
	$(MAKE) -C Engines/Gweled all -f GweledEngine.cbp.mak

visualbotngine: 
	$(MAKE) all -f VisualBotNGine.cbp.mak

clean: clean_engines_gweled_gweledengine clean_visualbotngine

clean_engines_gweled_gweledengine: 
	$(MAKE) -C Engines/Gweled clean -f GweledEngine.cbp.mak

clean_visualbotngine: 
	$(MAKE) clean -f VisualBotNGine.cbp.mak

.PHONY: clean_engines_gweled_gweledengine clean_visualbotngine

