#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`
MAKE = make

all: xwd_1_0_5_xwdlib engines_gweled_gweledengine visualbotngine

xwd_1_0_5_xwdlib: 
	$(MAKE) -C xwd-1.0.5 all -f XwdLib.cbp.mak

engines_gweled_gweledengine: 
	$(MAKE) -C Engines/Gweled all -f GweledEngine.cbp.mak

visualbotngine: 
	$(MAKE) all -f VisualBotNGine.cbp.mak

clean: clean_xwd_1_0_5_xwdlib clean_engines_gweled_gweledengine clean_visualbotngine

clean_xwd_1_0_5_xwdlib: 
	$(MAKE) -C xwd-1.0.5 clean -f XwdLib.cbp.mak

clean_engines_gweled_gweledengine: 
	$(MAKE) -C Engines/Gweled clean -f GweledEngine.cbp.mak

clean_visualbotngine: 
	$(MAKE) clean -f VisualBotNGine.cbp.mak

.PHONY: clean_xwd_1_0_5_xwdlib clean_engines_gweled_gweledengine clean_visualbotngine

